melk_tree_builder_index:
    pattern:  /
    defaults: { _controller: MelkTreeBuilderBundle:Default:index }

melk_tree_builder_tree:
    pattern:  /show
    defaults: { _controller: MelkTreeBuilderBundle:Default:tree }
    requirements:
      _method: POST
